#!/bin/bash

if ! voms-proxy-info -exists -hours 10 2> /dev/null; then
  echo 'create a proxy first'
  exit 1
fi

if [[ $# < 1 ]]; then
  echo "usage: $0 config_files number_of_events_per_config"
  exit 1
fi

# parse arguments
configfile=$1
icfilepath=$2
N=$3
label=`basename $configfile`
icfile=`basename $icfilepath`
# gridftp destination for all events in this batch
desturl="gsiftp://ntheoryfs01.phy.duke.edu/var/phy/project/nukeserv/wk42/Hybrid-3d-Bayesian/hydro-avg-PbPb-2/$label/"

# directory containing this script
startdir="/home/weiyao-ke/ebe-3d-osg/condor/"
echo $startdir
echo $label
echo $icfile
# create a "scratch" directory for all the condor files
scratchdir="/local-scratch/weiyao-ke/condor/Hybrid-3d-Bayesian/hydro-avg-PbPb/$label/"
mkdir -p $scratchdir

# Create a condor submit description file.  This is the "template" job file for
# every job in this batch with several $(...) variables to be set by the dag.
cat > $scratchdir/job <<EOF
universe = vanilla
x509userproxy = /tmp/x509up_u$(id --user)
+ProjectName = "Duke-QGP"

request_memory = 2G
request_disk = 3G
# requirements = (OpSysMajorVer >= 6) && (CVMFS_oasis_opensciencegrid_org_REVISION >= 4288)
# rank = KFlops
requirements = (OSGVO_OS_STRING == "RHEL 6") && (CVMFS_oasis_opensciencegrid_org_REVISION >= 5013)

should_transfer_files = YES
WhenToTransferOutput = ON_EXIT

executable = $startdir/job-control
arguments = $label $icfile \$(Process) $desturl

transfer_input_files = $startdir/../hic-3d-osg-cut.tar.gz, $startdir/$configfile, $startdir/$icfilepath
transfer_output_files = hic-3d-osg-cut/dndy-\$(Process).hdf5

output = $scratchdir/\$(Process).out
error = $scratchdir/\$(Process).err
log = $scratchdir/\$(Process).log

# periodic_release = (HoldReasonCode =?= 16)
# periodic_remove = (HoldReasonCode =?= 1) && (NumJobStarts >= 6)

queue $N
EOF

pushd $scratchdir
condor_submit job
popd
